#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Application.Resource", IsApplication=true)]

namespace Application
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Add = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int All = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int basket = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Black = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Blue = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Drunk_Lvl_1 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Drunk_Lvl_2 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Drunk_Lvl_3 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Drunk_Lvl_4 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Favorit = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Green = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Icon = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int im1 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int im10 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int im11 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int im2 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int im3 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int im4 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int im5 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int im6 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int im7 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int im8 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int im9 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int Purple = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int Red = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int Settings = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int Yellow = 2130837530;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050035
			public const int AddButton = 2131034165;
			
			// aapt resource value: 0x7f050038
			public const int MyButton = 2131034168;
			
			// aapt resource value: 0x7f05000d
			public const int alcoholSeekBar = 2131034125;
			
			// aapt resource value: 0x7f050013
			public const int alcoholTextView = 2131034131;
			
			// aapt resource value: 0x7f050023
			public const int colorButton1 = 2131034147;
			
			// aapt resource value: 0x7f050024
			public const int colorButton2 = 2131034148;
			
			// aapt resource value: 0x7f050025
			public const int colorButton3 = 2131034149;
			
			// aapt resource value: 0x7f050026
			public const int colorButton4 = 2131034150;
			
			// aapt resource value: 0x7f050027
			public const int colorButton5 = 2131034151;
			
			// aapt resource value: 0x7f050028
			public const int colorButton6 = 2131034152;
			
			// aapt resource value: 0x7f050036
			public const int fragmentContainer = 2131034166;
			
			// aapt resource value: 0x7f050016
			public const int horizontalScrollView1 = 2131034134;
			
			// aapt resource value: 0x7f050018
			public const int imageButton1 = 2131034136;
			
			// aapt resource value: 0x7f050021
			public const int imageButton10 = 2131034145;
			
			// aapt resource value: 0x7f050022
			public const int imageButton11 = 2131034146;
			
			// aapt resource value: 0x7f050019
			public const int imageButton2 = 2131034137;
			
			// aapt resource value: 0x7f05001a
			public const int imageButton3 = 2131034138;
			
			// aapt resource value: 0x7f05001b
			public const int imageButton4 = 2131034139;
			
			// aapt resource value: 0x7f05001c
			public const int imageButton5 = 2131034140;
			
			// aapt resource value: 0x7f05001d
			public const int imageButton6 = 2131034141;
			
			// aapt resource value: 0x7f05001e
			public const int imageButton7 = 2131034142;
			
			// aapt resource value: 0x7f05001f
			public const int imageButton8 = 2131034143;
			
			// aapt resource value: 0x7f050020
			public const int imageButton9 = 2131034144;
			
			// aapt resource value: 0x7f05003b
			public const int imageView1 = 2131034171;
			
			// aapt resource value: 0x7f050003
			public const int linear1 = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int linearLayout1 = 2131034117;
			
			// aapt resource value: 0x7f05000a
			public const int linearLayout10 = 2131034122;
			
			// aapt resource value: 0x7f05000c
			public const int linearLayout11 = 2131034124;
			
			// aapt resource value: 0x7f05000f
			public const int linearLayout12 = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int linearLayout13 = 2131034128;
			
			// aapt resource value: 0x7f050012
			public const int linearLayout14 = 2131034130;
			
			// aapt resource value: 0x7f050017
			public const int linearLayout15 = 2131034135;
			
			// aapt resource value: 0x7f05002a
			public const int linearLayout16 = 2131034154;
			
			// aapt resource value: 0x7f050029
			public const int linearLayout17 = 2131034153;
			
			// aapt resource value: 0x7f05002b
			public const int linearLayout18 = 2131034155;
			
			// aapt resource value: 0x7f05002c
			public const int linearLayout19 = 2131034156;
			
			// aapt resource value: 0x7f050008
			public const int linearLayout2 = 2131034120;
			
			// aapt resource value: 0x7f050032
			public const int linearLayout20 = 2131034162;
			
			// aapt resource value: 0x7f050034
			public const int linearLayout21 = 2131034164;
			
			// aapt resource value: 0x7f050015
			public const int linearLayout3 = 2131034133;
			
			// aapt resource value: 0x7f050041
			public const int linearLayout4 = 2131034177;
			
			// aapt resource value: 0x7f050002
			public const int linearLayout5 = 2131034114;
			
			// aapt resource value: 0x7f050007
			public const int linearLayout6 = 2131034119;
			
			// aapt resource value: 0x7f050014
			public const int linearLayout7 = 2131034132;
			
			// aapt resource value: 0x7f050009
			public const int linearLayout8 = 2131034121;
			
			// aapt resource value: 0x7f05000e
			public const int linearLayout9 = 2131034126;
			
			// aapt resource value: 0x7f050033
			public const int massSeekBar = 2131034163;
			
			// aapt resource value: 0x7f050006
			public const int nameTextView = 2131034118;
			
			// aapt resource value: 0x7f050037
			public const int progressView = 2131034167;
			
			// aapt resource value: 0x7f05003e
			public const int radioButton2_1 = 2131034174;
			
			// aapt resource value: 0x7f05003f
			public const int radioButton2_2 = 2131034175;
			
			// aapt resource value: 0x7f050040
			public const int radioButton2_3 = 2131034176;
			
			// aapt resource value: 0x7f05003d
			public const int radioGroup2 = 2131034173;
			
			// aapt resource value: 0x7f050000
			public const int scrollView = 2131034112;
			
			// aapt resource value: 0x7f05003c
			public const int seekBar1 = 2131034172;
			
			// aapt resource value: 0x7f050001
			public const int textView1 = 2131034113;
			
			// aapt resource value: 0x7f05002e
			public const int textView10 = 2131034158;
			
			// aapt resource value: 0x7f05002f
			public const int textView11 = 2131034159;
			
			// aapt resource value: 0x7f050030
			public const int textView12 = 2131034160;
			
			// aapt resource value: 0x7f050031
			public const int textView13 = 2131034161;
			
			// aapt resource value: 0x7f050039
			public const int textView2 = 2131034169;
			
			// aapt resource value: 0x7f050004
			public const int textView3 = 2131034116;
			
			// aapt resource value: 0x7f05003a
			public const int textView4 = 2131034170;
			
			// aapt resource value: 0x7f05000b
			public const int textView6 = 2131034123;
			
			// aapt resource value: 0x7f050011
			public const int textView7 = 2131034129;
			
			// aapt resource value: 0x7f05002d
			public const int textView9 = 2131034157;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddOption = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int All = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Content = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Favorite = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int MainMenu = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Setting = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
